name = "Titi"
license = "MIT"
licenselink = "https://github.com/datasketch/hugo-titi/blob/master/LICENSE.md"
description = "eXtremely Minimal Hugo theme: about 150 lines of code in total, including HTML and CSS"
homepage = "https://Titi.datasketch.name"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Datasketch"
  homepage = "https://datasketch.co"
