baseURL = "/"
languageCode = "es-es"
title = "Hugo Titi"
theme = "hugo-titi"
themesDir = "../.."
# googleAnalytics = ""

[params]
  [params.social]
    facebook = "https://es-la.facebook.com/datasketch/"
    twitter = "https://twitter.com/datasketch"
    email = "info@datasketch.co"
    always_visible = true

  [params.header]
    logo = "images/datasketch.svg"
    bg_color = ""
    text_color = "#ffffff"
    bg_color_class = "bg-gray-800"
    text_color_class = ""
    # One of
    # sticky: always sticky on top
    # normal: static positioned
    # mixed: sticky after first child element of #content is offscreen
    behavior = "sticky"
  
  [params.footer]
    # The path inside the static folder
    # Note there is no leading nor trailing slash
    logo = "images/datasketch-vertical.svg"

    bg_color = ""
    text_color = ""
    bg_color_class = "bg-gray-900"
    text_color_class = "text-white"

  [[params.fonts]]
    family = "Montserrat"
    weight = [400, 500]
  
  [[params.fonts]]
    family = "PT Serif"
